name: Sync Feedback

on:
  push:
    branches:
      - main   # Trigger this on push to the main branch
  schedule:
    - cron: "0 * * * *"  # Sync every hour (or adjust the schedule as needed)

jobs:
  sync-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Sync Feedback to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically created GitHub token
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git add ./feedback_data/feedback.csv
          git commit -m "Sync feedback data"
          git push origin main
